package ca.uqam.euler.nicolas.scala
/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
 * Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
 * Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 */
// Answer : 1533776805
object Problem045 {
//  import Stream._
//  class Numbers(var ns: Stream[Long]) {
//    def countains(n: Long) = {
//      ns = ns.dropWhile(_ < n)
//      ns.head == n
//    }
//  }
//  val ps = new Numbers(from(1) map { n ⇒ n.toLong * (3 * n - 1) / 2 })
//  val hs = new Numbers(from(1) map { n ⇒ n.toLong * (2 * n - 1) })
//  val ts = from(1) map { n ⇒ n.toLong * (n + 1) / 2 }
//  def main(args: Array[String]) {
//    println(
//      ts.drop(285)
//        .find(t ⇒ hs.countains(t) && ps.countains(t))
//        .get)
//  }
//
//  import java.util.Random
//  import scalaz._; import Scalaz._
//  def dice() = state[Random, Int](r ⇒ (r, r.nextInt(6) + 1))
//  def TwoDice() = for {
//    r1 ← dice()
//    r2 ← dice()
//  } yield (r1, r2)
//  val list = List.fill(10)(TwoDice())
//  type StateRandom[x] = State[Random,x]
//  val list2 = list.sequence[StateRandom, (Int, Int)]

}